#include "loader.hpp"

#include "utils.hpp"

#include <algorithm>
#include <array>
#include <cstdlib>
#include <sstream>
#include <string_view>
#include <type_traits>

namespace dcn::loader
{
    namespace
    {
        // Bump when PT Solidity changes affect generated bytecode semantics to invalidate cached artifacts.
        constexpr const char* PT_BUILD_VERSION = "pt-formats-005";

        const std::array<std::string, 3> PT_STORAGE_ENTITY_DIRS{
            "connectors",
            "transformations",
            "conditions"
        };

        struct JsonImportContext
        {
            absl::flat_hash_map<std::string, TransformationRecord> transformations;
            absl::flat_hash_map<std::string, ConditionRecord> conditions;
            absl::flat_hash_map<std::string, ConnectorRecord> connectors;

            absl::flat_hash_set<std::string> imported_transformations;
            absl::flat_hash_set<std::string> importing_transformations;

            absl::flat_hash_set<std::string> imported_conditions;
            absl::flat_hash_set<std::string> importing_conditions;

            absl::flat_hash_set<std::string> imported_connectors;
            absl::flat_hash_set<std::string> importing_connectors;

            LoaderBatchConfig batch_config{};
            std::vector<std::pair<chain::Address, TransformationRecord>> pending_transformations;
            std::vector<std::pair<chain::Address, ConditionRecord>> pending_conditions;
            std::vector<std::pair<chain::Address, ConnectorRecord>> pending_connectors;

            bool trace_enabled = false;
            std::vector<std::string> connector_import_stack;
        };

        struct ConnectorEnsureContext
        {
            absl::flat_hash_set<std::string> done;
            absl::flat_hash_set<std::string> visiting;

            bool trace_enabled = false;
            std::vector<std::string> connector_deploy_stack;
        };

        struct StackPushGuard
        {
            explicit StackPushGuard(std::vector<std::string> & stack, const std::string & value)
                : stack_ref(stack)
            {
                stack_ref.push_back(value);
            }

            ~StackPushGuard()
            {
                if(!stack_ref.empty())
                {
                    stack_ref.pop_back();
                }
            }

            StackPushGuard(const StackPushGuard &) = delete;
            StackPushGuard & operator=(const StackPushGuard &) = delete;

            std::vector<std::string> & stack_ref;
        };

        constexpr std::size_t MAX_CONNECTOR_IMPORT_DEPTH = 4096;

        static std::string formatDependencyStack(const std::vector<std::string> & stack)
        {
            if(stack.empty())
            {
                return "<empty>";
            }

            std::ostringstream oss;
            for(std::size_t i = 0; i < stack.size(); ++i)
            {
                if(i != 0)
                {
                    oss << " -> ";
                }
                oss << stack[i];
            }

            return oss.str();
        }

        static std::size_t normalizeBatchSize(std::size_t batch_size)
        {
            return (batch_size == 0) ? 1 : batch_size;
        }

        static bool isImportTraceEnabled()
        {
            const char * env_value = std::getenv("DECENTRALISED_ART_IMPORT_TRACE");
            if(env_value == nullptr)
            {
                return false;
            }

            const std::string_view flag(env_value);
            return !(flag.empty() ||
                flag == "0" ||
                flag == "false" ||
                flag == "FALSE" ||
                flag == "off" ||
                flag == "OFF");
        }

        static asio::awaitable<bool> flushPendingTransformations(
            storage::Registry & registry,
            JsonImportContext & context,
            bool force)
        {
            const std::size_t batch_size = normalizeBatchSize(context.batch_config.transformations);
            if(context.pending_transformations.empty() || (!force && context.pending_transformations.size() < batch_size))
            {
                if(context.trace_enabled && force)
                {
                    spdlog::info("JSON import flush transformations skipped: no pending records");
                }
                co_return true;
            }

            std::vector<std::pair<chain::Address, TransformationRecord>> batch;
            batch.swap(context.pending_transformations);
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON import flushing {} transformation(s), force={}, threshold={}",
                    batch.size(),
                    force,
                    batch_size);
            }
            if(!co_await registry.addTransformationsBatch(std::move(batch), false))
            {
                spdlog::error("Failed to batch-register imported transformations");
                co_return false;
            }

            co_return true;
        }

        static asio::awaitable<bool> flushPendingConditions(
            storage::Registry & registry,
            JsonImportContext & context,
            bool force)
        {
            const std::size_t batch_size = normalizeBatchSize(context.batch_config.conditions);
            if(context.pending_conditions.empty() || (!force && context.pending_conditions.size() < batch_size))
            {
                if(context.trace_enabled && force)
                {
                    spdlog::info("JSON import flush conditions skipped: no pending records");
                }
                co_return true;
            }

            std::vector<std::pair<chain::Address, ConditionRecord>> batch;
            batch.swap(context.pending_conditions);
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON import flushing {} condition(s), force={}, threshold={}",
                    batch.size(),
                    force,
                    batch_size);
            }
            if(!co_await registry.addConditionsBatch(std::move(batch), false))
            {
                spdlog::error("Failed to batch-register imported conditions");
                co_return false;
            }

            co_return true;
        }

        static asio::awaitable<bool> flushPendingConnectors(
            storage::Registry & registry,
            JsonImportContext & context,
            bool force)
        {
            const std::size_t batch_size = normalizeBatchSize(context.batch_config.connectors);
            if(context.pending_connectors.empty() || (!force && context.pending_connectors.size() < batch_size))
            {
                if(context.trace_enabled && force)
                {
                    spdlog::info("JSON import flush connectors skipped: no pending records");
                }
                co_return true;
            }

            std::vector<std::pair<chain::Address, ConnectorRecord>> batch;
            batch.swap(context.pending_connectors);
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON import flushing {} connector(s), force={}, threshold={}",
                    batch.size(),
                    force,
                    batch_size);
            }
            if(!co_await registry.addConnectorsBatch(std::move(batch), false))
            {
                spdlog::error("Failed to batch-register imported connectors");
                co_return false;
            }

            co_return true;
        }

        static std::vector<std::uint8_t> makeSingleStringCallInput(
            const std::string_view signature,
            const std::string & value)
        {
            std::vector<std::uint8_t> input_data;
            const auto selector = chain::constructSelector(std::string(signature));
            input_data.insert(input_data.end(), selector.begin(), selector.end());

            std::vector<std::uint8_t> offset(32, 0);
            offset[31] = 0x20;
            input_data.insert(input_data.end(), offset.begin(), offset.end());

            const auto encoded_value = evm::encodeAsArg(value);
            input_data.insert(input_data.end(), encoded_value.begin(), encoded_value.end());
            return input_data;
        }

        static std::optional<bool> parseBoolWord(const std::vector<std::uint8_t> & output)
        {
            if(output.size() < 32)
            {
                return std::nullopt;
            }

            return output.back() != 0;
        }

        static asio::awaitable<std::optional<bool>> containsRegistryEntry(
            evm::EVM & evm,
            const std::string_view signature,
            const std::string & name)
        {
            auto input_data = makeSingleStringCallInput(signature, name);
            co_await evm.setGas(evm.getRegistryAddress(), evm::DEFAULT_GAS_LIMIT);
            const auto exec_result = co_await evm.execute(
                evm.getRegistryAddress(),
                evm.getRegistryAddress(),
                std::move(input_data),
                evm::DEFAULT_GAS_LIMIT,
                0);
            if(!exec_result)
            {
                spdlog::error(
                    "Failed to call registry contains method '{}' for '{}': {}",
                    signature,
                    name,
                    static_cast<int>(exec_result.error().kind));
                co_return std::nullopt;
            }

            const auto parsed = parseBoolWord(exec_result.value());
            if(!parsed.has_value())
            {
                spdlog::error(
                    "Failed to parse contains result '{}' for '{}': invalid ABI output size={}",
                    signature,
                    name,
                    exec_result.value().size());
                co_return std::nullopt;
            }

            co_return parsed;
        }
    }

    asio::awaitable<bool> ensureTransformationImported(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        JsonImportContext & context);
    asio::awaitable<bool> ensureConditionImported(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        JsonImportContext & context);
    asio::awaitable<bool> ensureConnectorImported(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        JsonImportContext & context);
    asio::awaitable<bool> ensureConnectorDeployedImpl(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        ConnectorEnsureContext & context);
    static asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployConnectorWithContext(
        evm::EVM & evm,
        storage::Registry & registry,
        ConnectorRecord connector_record,
        const std::filesystem::path & storage_path,
        bool register_in_registry,
        bool persist_json,
        ConnectorEnsureContext & ensure_context);

    template<class T>
    static absl::flat_hash_map<std::string, T> _loadJSONRecords(std::filesystem::path dir)
    {
        absl::flat_hash_map<std::string, T> loaded_data;
        parse::Result<T> loaded_result;
        const bool trace_enabled = isImportTraceEnabled();
        std::size_t json_files_seen = 0;
        std::size_t loaded_records = 0;
        std::size_t open_failures = 0;
        std::size_t parse_failures = 0;
        
        bool success = true;

        try {
            for (const auto& entry : std::filesystem::directory_iterator(dir)) 
            {
                if(!entry.is_regular_file() || entry.path().extension() != ".json")
                {
                    continue;
                }

                ++json_files_seen;
                
                spdlog::debug(std::format("Found JSON file: {}", entry.path().string()));
                if(trace_enabled)
                {
                    spdlog::info("JSON import scanning file '{}'", entry.path().string());
                }

                std::ifstream file(entry.path());

                if(!file.is_open())
                {
                    spdlog::error(std::format("Failed to open file: {}", entry.path().string()));
                    ++open_failures;
                    continue;
                }

                std::string json((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
                file.close();

                loaded_result = parse::parseFromJson<T>(json, parse::use_protobuf);
                if(!loaded_result)
                {
                    spdlog::error(std::format("Failed to parse JSON: {}", json));
                    ++parse_failures;
                    continue;
                }

                loaded_data.try_emplace(entry.path().stem().string(), std::move(*loaded_result));
                ++loaded_records;
            }
        } 
        catch (const std::filesystem::filesystem_error& e) 
        {
            spdlog::error(std::format("Filesystem error: {}", e.what()));
            success = false;
        } 
        catch (const std::exception& e) 
        {
            spdlog::error(std::format("Exception: {}", e.what()));
            success = false;
        }

        if(!success)
        {
            return {};
        }

        spdlog::info(
            "JSON import scan finished for '{}': files={}, loaded={}, open_failures={}, parse_failures={}",
            dir.string(),
            json_files_seen,
            loaded_records,
            open_failures,
            parse_failures);

        return loaded_data;
    }

    static void _removeFileNoThrow(const std::filesystem::path & file_path)
    {
        std::error_code ec;
        std::filesystem::remove(file_path, ec);
        if(ec)
        {
            spdlog::debug("Failed to remove '{}': {}", file_path.string(), ec.message());
        }
    }

    static void _loadCleanup(const std::filesystem::path & out_dir, const std::string & name)
    {
        // remove binary file
        _removeFileNoThrow(out_dir / (name + ".bin"));
        _removeFileNoThrow(out_dir / (name + ".abi"));
    }

    bool ensurePTBuildVersion(const std::filesystem::path & storage_path)
    {
        const std::filesystem::path marker_path = storage_path / "pt_solidity_build_version";

        std::string current_version;
        if(std::filesystem::exists(marker_path))
        {
            std::ifstream marker_in(marker_path);
            if(marker_in.is_open())
            {
                std::getline(marker_in, current_version);
            }
        }

        if(current_version == PT_BUILD_VERSION)
        {
            spdlog::debug("PT Solidity build cache version is up-to-date: {}", PT_BUILD_VERSION);
            return true;
        }

        spdlog::info(
            "PT Solidity build cache version changed from '{}' to '{}'. Cleaning stale build artifacts.",
            current_version.empty() ? "<none>" : current_version,
            PT_BUILD_VERSION
        );

        try
        {
            for(const std::string & entity_dir : PT_STORAGE_ENTITY_DIRS)
            {
                const std::filesystem::path build_dir = storage_path / entity_dir / "build";
                std::size_t removed_count = 0;

                if(std::filesystem::exists(build_dir))
                {
                    for(const auto & entry : std::filesystem::directory_iterator(build_dir))
                    {
                        if(!entry.is_regular_file())
                        {
                            continue;
                        }

                        const std::filesystem::path file_path = entry.path();
                        const std::string ext = file_path.extension().string();
                        if(ext == ".bin" || ext == ".abi")
                        {
                            std::filesystem::remove(file_path);
                            ++removed_count;
                        }
                    }
                }

                spdlog::info("PT build cleanup '{}': removed {} cached artifacts", entity_dir, removed_count);
            }
        }
        catch(const std::filesystem::filesystem_error & e)
        {
            spdlog::error("Failed to cleanup PT build artifacts: {}", e.what());
            return false;
        }

        std::ofstream marker_out(marker_path, std::ios::out | std::ios::trunc);
        if(!marker_out.is_open())
        {
            spdlog::error("Failed to write PT build version marker '{}'", marker_path.string());
            return false;
        }

        marker_out << PT_BUILD_VERSION;
        marker_out.close();

        spdlog::info("PT Solidity build cache marker updated: {}", PT_BUILD_VERSION);
        return true;
    }

    template<class RecordType>
    static asio::awaitable<bool> _saveJsonRecord(const std::string & name, RecordType record, const std::filesystem::path out_dir)
    {
        if(std::filesystem::exists(out_dir) == false)
        {
            spdlog::error("Directory {} does not exists", out_dir.string());
            co_return false;
        }

        const auto parsing_result = parse::parseToJson(record, parse::use_protobuf);
        if(!parsing_result)
        {
            spdlog::error("Failed to parse record `{}`", name);
            co_return false;
        }

        std::ofstream output_file(out_dir / (name + ".json"), std::ios::out | std::ios::trunc);

        output_file << *parsing_result;
        output_file.close();

        co_return true;
    }

    // template<class RecordType, class CodeGeneratorFunc>
    // static asio::awaitable<bool> _compileRecord(const std::string & name, RecordType record, 
    //     CodeGeneratorFunc && constructSolidityCode,
    //     const std::filesystem::path bin_dir)
    // {
    //     // if binary file does not exist
    //     if(std::filesystem::exists(bin_dir / (name + ".bin")) == false)
    //     {
    //         // there is a need for compile code
    //         const std::filesystem::path code_path = bin_dir / (name + ".sol");

    //         // create code file
    //         std::ofstream out_file(code_path); 
    //         if(!out_file.is_open())
    //         {
    //             spdlog::error("Failed to create file");
    //             co_return std::unexpected(evm::DeployError{});
    //         }

    //         out_file << constructSolidityCode(record.connector());
    //         out_file.close();

    //         // compile code
    //         if(!co_await evm.compile(code_path, bin_dir, file::getPTPath()/ "contracts"))
    //         {
    //             spdlog::error("Failed to compile code");
    //             // remove code file
    //             std::filesystem::remove(code_path);
    //             co_return std::unexpected(evm::DeployError{evm::DeployError::Kind::COMPILATION_ERROR});
    //         }

    //         // remove code file
    //         std::filesystem::remove(code_path);
    //     }
    // }



    template<class T, class InternalGetter, class SolidityCodeCtor>
    static asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> _deployObjectLocally(evm::EVM & evm, 
        storage::Registry & registry, T object, InternalGetter getter,
        const std::filesystem::path out_dir, SolidityCodeCtor solidity_code_ctor, pt::PTDeployError::Kind expected_conflict_error
        , bool register_in_registry = true,
        bool persist_json = true
    )
    {
        using Internal_t = std::invoke_result_t<InternalGetter, T>;
        const Internal_t & internal = std::invoke(getter, object);
        spdlog::debug("_deployObjectLocally '{}'", internal.name());

        if(internal.name().empty())
        {
            spdlog::error("Object name is empty");
            co_return std::unexpected(pt::PTDeployError{
                .kind = pt::PTDeployError::Kind::INVALID_INPUT});
        }

        const std::string name = internal.name();

        const auto address_result = evmc::from_hex<chain::Address>(object.owner());
        if(!address_result)
        {
            spdlog::error("Failed to parse address");
            co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
        }
        const auto & address = *address_result;

        const std::filesystem::path bin_dir = out_dir / "build";

        if(std::filesystem::exists(bin_dir) == false)
        {
            spdlog::error("Directory {} does not exists", bin_dir.string());
            co_return std::unexpected(pt::PTDeployError{});
        }

        // if binary file does not exist
        const bool binary_already_exists = std::filesystem::exists(bin_dir / (name + ".bin"));
        const auto cleanup_new_build_artifacts = [&]()
        {
            if(!binary_already_exists)
            {
                _loadCleanup(bin_dir, name);
            }
        };

        if(binary_already_exists == false)
        {
            // there is a need for compile code
            const std::filesystem::path code_path = bin_dir / (name + ".sol");

            // create code file
            std::ofstream out_file(code_path); 
            if(!out_file.is_open())
            {
                spdlog::error("Failed to create file");
                co_return std::unexpected(pt::PTDeployError{});
            }

            using SolidityCodeResult_t = std::decay_t<std::invoke_result_t<SolidityCodeCtor, Internal_t>>;
            const auto solidity_code_result = std::invoke(std::forward<SolidityCodeCtor>(solidity_code_ctor), internal);

            std::string solidity_code;
            if constexpr(std::is_same_v<SolidityCodeResult_t, parse::Result<std::string>>)
            {
                if(!solidity_code_result)
                {
                    spdlog::error(
                        "Failed to construct Solidity code for `{}`: parse error kind={} ({})",
                        name,
                        static_cast<int>(solidity_code_result.error().kind),
                        solidity_code_result.error().message);
                    out_file.close();
                    _removeFileNoThrow(code_path);
                    co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
                }

                solidity_code = *solidity_code_result;
            }
            else if constexpr(std::is_same_v<SolidityCodeResult_t, std::string>)
            {
                solidity_code = solidity_code_result;
                if(solidity_code.empty())
                {
                    spdlog::error("Failed to construct Solidity code for `{}`: empty source", name);
                    out_file.close();
                    _removeFileNoThrow(code_path);
                    co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
                }
            }
            else
            {
                static_assert(utils::always_false<SolidityCodeResult_t>, "Unsupported Solidity code constructor return type");
            }

            out_file << solidity_code;
            if(!out_file.good())
            {
                spdlog::error("Failed to write Solidity source file '{}'", code_path.string());
                out_file.close();
                _removeFileNoThrow(code_path);
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
            }
            out_file.close();
            if(out_file.fail())
            {
                spdlog::error("Failed to flush Solidity source file '{}'", code_path.string());
                _removeFileNoThrow(code_path);
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
            }

            // compile code
            if(!co_await evm.compile(code_path, bin_dir, evm.getPTPath() / "contracts", evm.getPTPath() / "node_modules"))
            {
                spdlog::error("Failed to compile code");
                // remove code file
                _removeFileNoThrow(code_path);
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{ pt::PTDeployError::Kind::INVALID_INPUT});
            }

            // remove code file
            _removeFileNoThrow(code_path);
        }

        co_await evm.addAccount(address, evm::DEFAULT_GAS_LIMIT);
        co_await evm.setGas(address, evm::DEFAULT_GAS_LIMIT);
        
        std::vector<std::uint8_t> ctor_args = evm::encodeAsArg(evm.getRegistryAddress());
        auto deploy_res = co_await evm.deploy(
            bin_dir / (name + ".bin"),
            address, 
            std::move(ctor_args),
            evm::DEFAULT_GAS_LIMIT, 
            0);

        if(!deploy_res)
        {
            spdlog::error(std::format("Failed to deploy object: {}", static_cast<int>(deploy_res.error().kind)));
            const auto & error = deploy_res.error();
            const auto pt_error = parse::decodeBytes<pt::PTDeployError>(error.result_bytes);

            if(!pt_error)
            {
                std::string output_hex = "<empty>";
                if(!error.result_bytes.empty())
                {
                    output_hex = evmc::hex(evmc::bytes_view{error.result_bytes.data(), error.result_bytes.size()});
                }

                spdlog::error(std::format(
                    "Failed to parse PTDeployError: {} ({}) output={}",
                    static_cast<int>(pt_error.error().kind),
                    pt_error.error().message,
                    output_hex));
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{});
            }

            if(pt_error->kind != expected_conflict_error)
            {
                cleanup_new_build_artifacts();
            }

            co_return std::unexpected(pt_error.value());
        }

        const auto object_address = deploy_res.value();
        spdlog::info("Object address '{}': {}", name, evmc::hex(object_address));

        const auto owner_result = co_await fetchOwner(evm, object_address);

        // check execution status
        if(!owner_result)
        {
            spdlog::error(std::format("Failed to fetch owner {}", static_cast<int>(owner_result.error().kind)));

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{});
        }

        const auto owner_address_res = chain::readAddressWord(owner_result.value());

        if(!owner_address_res)
        {
            spdlog::error("Failed to parse owner address");

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
        }

        const auto & owner_address = owner_address_res.value();

        if(owner_address != address)
        {
            spdlog::error("Owner address mismatch");

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
        }

        if(register_in_registry && !co_await registry.add(object_address, object))
        {
            spdlog::error("Failed to add object '{}'", name);

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{});
        }
        
        if(persist_json && !co_await _saveJsonRecord(name, std::move(object), out_dir))
        {
            spdlog::error("Failed to save object json '{}'", name);

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{});
        }

        spdlog::debug("Object '{}' added", name);
        co_return object_address;
    }


    static asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployConnectorWithContext(
        evm::EVM & evm,
        storage::Registry & registry,
        ConnectorRecord connector_record,
        const std::filesystem::path & storage_path,
        bool register_in_registry,
        bool persist_json,
        ConnectorEnsureContext & ensure_context)
    {
        const Connector & connector = connector_record.connector();
        if(ensure_context.trace_enabled)
        {
            spdlog::info(
                "JSON import deploy connector '{}': validating dependencies before deploy",
                connector.name());
        }

        for(const auto & dimension : connector.dimensions())
        {
            for(const auto & transformation : dimension.transformations())
            {
                const std::string & transformation_name = transformation.name();
                if(transformation_name.empty())
                {
                    continue;
                }

                if(!co_await ensureTransformationDeployed(evm, registry, transformation_name, storage_path))
                {
                    spdlog::error(
                        "Cannot deploy connector '{}': dependency transformation '{}' is not deployable",
                        connector.name(),
                        transformation_name);
                    co_return std::unexpected(pt::PTDeployError{.kind = pt::PTDeployError::Kind::TRANSFORMATION_MISSING});
                }
            }

            if(!dimension.composite().empty())
            {
                if(!co_await ensureConnectorDeployedImpl(
                    evm,
                    registry,
                    dimension.composite(),
                    storage_path,
                    ensure_context))
                {
                    spdlog::error(
                        "Cannot deploy connector '{}': dependency connector '{}' is not deployable",
                        connector.name(),
                        dimension.composite());
                    co_return std::unexpected(pt::PTDeployError{.kind = pt::PTDeployError::Kind::CONNECTOR_MISSING});
                }
            }

            for(const auto & [_, binding_target] : dimension.bindings())
            {
                if(binding_target.empty())
                {
                    continue;
                }

                if(!co_await ensureConnectorDeployedImpl(
                    evm,
                    registry,
                    binding_target,
                    storage_path,
                    ensure_context))
                {
                    spdlog::error(
                        "Cannot deploy connector '{}': binding dependency connector '{}' is not deployable",
                        connector.name(),
                        binding_target);
                    co_return std::unexpected(pt::PTDeployError{.kind = pt::PTDeployError::Kind::CONNECTOR_MISSING});
                }
            }
        }

        if(!connector.condition_name().empty())
        {
            if(!co_await ensureConditionDeployed(evm, registry, connector.condition_name(), storage_path))
            {
                spdlog::error(
                    "Cannot deploy connector '{}': dependency condition '{}' is not deployable",
                    connector.name(),
                    connector.condition_name());
                co_return std::unexpected(pt::PTDeployError{.kind = pt::PTDeployError::Kind::CONDITION_MISSING});
            }
        }

        co_return co_await _deployObjectLocally(
            evm,
            registry,
            std::move(connector_record),
            &ConnectorRecord::connector,
            storage_path / "connectors",
            &constructConnectorSolidityCode,
            pt::PTDeployError::Kind::CONNECTOR_ALREADY_REGISTERED,
            register_in_registry,
            persist_json);
    }

    asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployConnector(
        evm::EVM & evm,
        storage::Registry & registry,
        ConnectorRecord connector_record,
        const std::filesystem::path & storage_path,
        bool register_in_registry,
        bool persist_json)
    {
        ConnectorEnsureContext ensure_context;
        ensure_context.trace_enabled = isImportTraceEnabled();
        ensure_context.connector_deploy_stack.reserve(64);
        co_return co_await deployConnectorWithContext(
            evm,
            registry,
            std::move(connector_record),
            storage_path,
            register_in_registry,
            persist_json,
            ensure_context);
    }

    asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployTransformation(
        evm::EVM & evm,
        storage::Registry & registry,
        TransformationRecord transformation_record,
        const std::filesystem::path & storage_path,
        bool register_in_registry,
        bool persist_json)
    {
        return _deployObjectLocally(evm,
            registry, 
            std::move(transformation_record), 
            &TransformationRecord::transformation, 
            storage_path / "transformations",
            &constructTransformationSolidityCode,
            pt::PTDeployError::Kind::TRANSFORMATION_ALREADY_REGISTERED,
            register_in_registry,
            persist_json);
    }


    asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployCondition(
        evm::EVM & evm,
        storage::Registry & registry,
        ConditionRecord condition_record,
        const std::filesystem::path & storage_path,
        bool register_in_registry,
        bool persist_json)
    {
        return _deployObjectLocally(evm,
            registry, 
            std::move(condition_record), 
            &ConditionRecord::condition, 
            storage_path / "conditions",
            &constructConditionSolidityCode,
            pt::PTDeployError::Kind::CONDITION_ALREADY_REGISTERED,
            register_in_registry,
            persist_json);
    }


    asio::awaitable<bool> loadStoredConnectors(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::filesystem::path & storage_path,
        std::size_t registry_batch_size)
    {
        spdlog::info("Loading stored connectors...");

        if(registry_batch_size == 0)
        {
            registry_batch_size = 1;
        }

        auto loaded_connectors = _loadJSONRecords<ConnectorRecord>(storage_path / "connectors");
        if(loaded_connectors.empty())
        {
            co_return false;
        }

        const auto sorted_connectors = utils::topologicalSort<ConnectorRecord, std::string, std::vector>(
                loaded_connectors,
                [](const ConnectorRecord & record)
                {
                    std::vector<std::string> dependencies;
                    dependencies.reserve(static_cast<std::size_t>(record.connector().dimensions_size()));
                    for(const auto & dimension : record.connector().dimensions())
                    {
                        if(dimension.composite().empty())
                        {
                            if(dimension.bindings_size() != 0)
                            {
                                for(const auto & [_, binding_target] : dimension.bindings())
                                {
                                    if(!binding_target.empty())
                                    {
                                        dependencies.push_back(binding_target);
                                    }
                                }
                            }
                            continue;
                        }

                        dependencies.push_back(dimension.composite());

                        for(const auto & [_, binding_target] : dimension.bindings())
                        {
                            if(binding_target.empty())
                            {
                                continue;
                            }
                            dependencies.push_back(binding_target);
                        }
                    }
                    return dependencies;
                },
                [](const std::string & composite) {return composite;}
            );

        bool success = true;
        std::size_t i = 0;
        const std::size_t progress_batch_size = (sorted_connectors.size() / 100) + 1;
        assert(progress_batch_size > 0);
        std::vector<std::pair<chain::Address, ConnectorRecord>> registry_batch;
        registry_batch.reserve(std::min<std::size_t>(registry_batch_size, sorted_connectors.size()));
        
        for(const auto & name : sorted_connectors)
        {
            const auto deploy_result = co_await deployConnector(
                evm,
                registry,
                loaded_connectors.at(name),
                storage_path,
                false,
                false);
            if(!deploy_result)
            {
                spdlog::error("Failed to deploy connector `{}`", name);
                success = false;
            }
            else
            {
                registry_batch.emplace_back(deploy_result.value(), std::move(loaded_connectors.at(name)));
                if(registry_batch.size() >= registry_batch_size)
                {
                    std::vector<std::pair<chain::Address, ConnectorRecord>> batch_to_insert;
                    batch_to_insert.swap(registry_batch);
                    if(!co_await registry.addConnectorsBatch(std::move(batch_to_insert), false))
                    {
                        spdlog::error("Failed to batch-register loaded connectors");
                        success = false;
                    }
                }
            }

            if(++i % progress_batch_size == 0) {spdlog::debug("{}/{} connectors loaded", i, loaded_connectors.size());}
        }

        if(!registry_batch.empty())
        {
            if(!co_await registry.addConnectorsBatch(std::move(registry_batch), false))
            {
                spdlog::error("Failed to batch-register loaded connectors");
                success = false;
            }
        }

        co_return success;
    }


    asio::awaitable<bool> loadStoredTransformations(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::filesystem::path & storage_path,
        std::size_t registry_batch_size)
    {
        spdlog::info("Loading stored transformations...");

        if(registry_batch_size == 0)
        {
            registry_batch_size = 1;
        }

        auto loaded_transformations = _loadJSONRecords<TransformationRecord>(storage_path / "transformations");
        if(loaded_transformations.empty())
        {
            co_return false;
        }

        bool success = true;
        std::size_t i = 0;
        const std::size_t progress_batch_size = (loaded_transformations.size() / 100) + 1;
        assert(progress_batch_size > 0);
        std::vector<std::pair<chain::Address, TransformationRecord>> registry_batch;
        registry_batch.reserve(std::min<std::size_t>(registry_batch_size, loaded_transformations.size()));

        for(auto & [name, transformation] : loaded_transformations)
        {
            const auto deploy_result = co_await deployTransformation(
                evm,
                registry,
                transformation,
                storage_path,
                false,
                false);
            if(!deploy_result)
            {
                spdlog::error("Failed to deploy transformation `{}`", name);
                success = false;
            }
            else
            {
                registry_batch.emplace_back(deploy_result.value(), std::move(transformation));
                if(registry_batch.size() >= registry_batch_size)
                {
                    std::vector<std::pair<chain::Address, TransformationRecord>> batch_to_insert;
                    batch_to_insert.swap(registry_batch);
                    if(!co_await registry.addTransformationsBatch(std::move(batch_to_insert), false))
                    {
                        spdlog::error("Failed to batch-register loaded transformations");
                        success = false;
                    }
                }
            }

            if(++i % progress_batch_size == 0) {spdlog::debug("{}/{} transformations loaded", i, loaded_transformations.size());}
        }

        if(!registry_batch.empty())
        {
            if(!co_await registry.addTransformationsBatch(std::move(registry_batch), false))
            {
                spdlog::error("Failed to batch-register loaded transformations");
                success = false;
            }
        }

        co_return success;
    }

    asio::awaitable<bool> loadStoredConditions(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::filesystem::path & storage_path,
        std::size_t registry_batch_size)
    {
        spdlog::info("Loading stored conditions...");

        if(registry_batch_size == 0)
        {
            registry_batch_size = 1;
        }

        auto loaded_conditions = _loadJSONRecords<ConditionRecord>(storage_path / "conditions");
        if(loaded_conditions.empty())
        {
            co_return false;
        }

        bool success = true;
        std::size_t i = 0;
        const std::size_t progress_batch_size = (loaded_conditions.size() / 100) + 1;
        assert(progress_batch_size > 0);
        std::vector<std::pair<chain::Address, ConditionRecord>> registry_batch;
        registry_batch.reserve(std::min<std::size_t>(registry_batch_size, loaded_conditions.size()));

        for(auto & [name, condition] : loaded_conditions)
        {
            const auto deploy_result = co_await deployCondition(
                evm,
                registry,
                condition,
                storage_path,
                false,
                false);
            if(!deploy_result)
            {
                spdlog::error("Failed to deploy condition `{}`", name);
                success = false;
            }
            else
            {
                registry_batch.emplace_back(deploy_result.value(), std::move(condition));
                if(registry_batch.size() >= registry_batch_size)
                {
                    std::vector<std::pair<chain::Address, ConditionRecord>> batch_to_insert;
                    batch_to_insert.swap(registry_batch);
                    if(!co_await registry.addConditionsBatch(std::move(batch_to_insert), false))
                    {
                        spdlog::error("Failed to batch-register loaded conditions");
                        success = false;
                    }
                }
            }

            if(++i % progress_batch_size == 0) {spdlog::debug("{}/{} conditions loaded", i, loaded_conditions.size());}
        }

        if(!registry_batch.empty())
        {
            if(!co_await registry.addConditionsBatch(std::move(registry_batch), false))
            {
                spdlog::error("Failed to batch-register loaded conditions");
                success = false;
            }
        }

        co_return success;
    }

    asio::awaitable<bool> ensureTransformationDeployed(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path)
    {
        if(name.empty())
        {
            spdlog::error("Cannot deploy transformation with empty name");
            co_return false;
        }

        const auto contains_res = co_await containsRegistryEntry(evm, "containsTransformation(string)", name);
        if(!contains_res.has_value())
        {
            co_return false;
        }
        if(*contains_res)
        {
            co_return true;
        }

        const auto record_handle_opt = co_await registry.getTransformationRecordHandle(name);
        if(!record_handle_opt.has_value() || !(*record_handle_opt))
        {
            spdlog::error("Transformation '{}' is missing in registry DB", name);
            co_return false;
        }

        const auto deploy_result = co_await deployTransformation(
            evm,
            registry,
            *(*record_handle_opt),
            storage_path,
            false,
            false);
        if(!deploy_result &&
            deploy_result.error().kind != pt::PTDeployError::Kind::TRANSFORMATION_ALREADY_REGISTERED)
        {
            spdlog::error(
                "Failed to deploy transformation '{}' from DB for runtime use: {}",
                name,
                static_cast<int>(deploy_result.error().kind));
            co_return false;
        }

        co_return true;
    }

    asio::awaitable<bool> ensureConditionDeployed(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path)
    {
        if(name.empty())
        {
            co_return true;
        }

        const auto contains_res = co_await containsRegistryEntry(evm, "containsCondition(string)", name);
        if(!contains_res.has_value())
        {
            co_return false;
        }
        if(*contains_res)
        {
            co_return true;
        }

        const auto record_handle_opt = co_await registry.getConditionRecordHandle(name);
        if(!record_handle_opt.has_value() || !(*record_handle_opt))
        {
            spdlog::error("Condition '{}' is missing in registry DB", name);
            co_return false;
        }

        const auto deploy_result = co_await deployCondition(
            evm,
            registry,
            *(*record_handle_opt),
            storage_path,
            false,
            false);
        if(!deploy_result &&
            deploy_result.error().kind != pt::PTDeployError::Kind::CONDITION_ALREADY_REGISTERED)
        {
            spdlog::error(
                "Failed to deploy condition '{}' from DB for runtime use: {}",
                name,
                static_cast<int>(deploy_result.error().kind));
            co_return false;
        }

        co_return true;
    }

    asio::awaitable<bool> ensureConnectorDeployed(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path)
    {
        ConnectorEnsureContext context;
        context.trace_enabled = isImportTraceEnabled();
        context.connector_deploy_stack.reserve(64);
        co_return co_await ensureConnectorDeployedImpl(evm, registry, name, storage_path, context);
    }

    asio::awaitable<bool> importJsonStorageToDatabase(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::filesystem::path & storage_path,
        LoaderBatchConfig batch_config)
    {
        JsonImportContext context;
        context.trace_enabled = isImportTraceEnabled();
        context.connector_import_stack.reserve(64);
        context.batch_config.connectors = normalizeBatchSize(batch_config.connectors);
        context.batch_config.transformations = normalizeBatchSize(batch_config.transformations);
        context.batch_config.conditions = normalizeBatchSize(batch_config.conditions);

        spdlog::info(
            "JSON storage import start: storage_path='{}', batch(connectors={}, transformations={}, conditions={})",
            storage_path.string(),
            context.batch_config.connectors,
            context.batch_config.transformations,
            context.batch_config.conditions);

        context.transformations = _loadJSONRecords<TransformationRecord>(storage_path / "transformations");
        context.conditions = _loadJSONRecords<ConditionRecord>(storage_path / "conditions");
        context.connectors = _loadJSONRecords<ConnectorRecord>(storage_path / "connectors");

        context.pending_transformations.reserve(std::min<std::size_t>(context.batch_config.transformations, context.transformations.size()));
        context.pending_conditions.reserve(std::min<std::size_t>(context.batch_config.conditions, context.conditions.size()));
        context.pending_connectors.reserve(std::min<std::size_t>(context.batch_config.connectors, context.connectors.size()));

        std::vector<std::string> transformation_names;
        transformation_names.reserve(context.transformations.size());
        for(const auto & [name, _] : context.transformations)
        {
            transformation_names.push_back(name);
        }
        std::ranges::sort(transformation_names);

        std::vector<std::string> condition_names;
        condition_names.reserve(context.conditions.size());
        for(const auto & [name, _] : context.conditions)
        {
            condition_names.push_back(name);
        }
        std::ranges::sort(condition_names);

        std::vector<std::string> connector_names;
        connector_names.reserve(context.connectors.size());
        for(const auto & [name, _] : context.connectors)
        {
            connector_names.push_back(name);
        }
        std::ranges::sort(connector_names);

        spdlog::info(
            "JSON storage import inventory: transformations={}, conditions={}, connectors={}",
            transformation_names.size(),
            condition_names.size(),
            connector_names.size());
        if(context.trace_enabled)
        {
            spdlog::info("JSON storage import trace enabled (DECENTRALISED_ART_IMPORT_TRACE)");
        }

        bool success = true;

        for(std::size_t i = 0; i < transformation_names.size(); ++i)
        {
            const auto & name = transformation_names[i];
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON storage import transformation {}/{}: '{}'",
                    i + 1,
                    transformation_names.size(),
                    name);
            }

            try
            {
                if(!co_await ensureTransformationImported(evm, registry, name, storage_path, context))
                {
                    success = false;
                }
            }
            catch(const std::exception & e)
            {
                spdlog::error("Unhandled exception while importing transformation '{}': {}", name, e.what());
                success = false;
            }
            catch(...)
            {
                spdlog::error("Unhandled unknown exception while importing transformation '{}'", name);
                success = false;
            }
        }
        if(!co_await flushPendingTransformations(registry, context, true))
        {
            success = false;
        }

        for(std::size_t i = 0; i < condition_names.size(); ++i)
        {
            const auto & name = condition_names[i];
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON storage import condition {}/{}: '{}'",
                    i + 1,
                    condition_names.size(),
                    name);
            }

            try
            {
                if(!co_await ensureConditionImported(evm, registry, name, storage_path, context))
                {
                    success = false;
                }
            }
            catch(const std::exception & e)
            {
                spdlog::error("Unhandled exception while importing condition '{}': {}", name, e.what());
                success = false;
            }
            catch(...)
            {
                spdlog::error("Unhandled unknown exception while importing condition '{}'", name);
                success = false;
            }
        }
        if(!co_await flushPendingConditions(registry, context, true))
        {
            success = false;
        }

        for(std::size_t i = 0; i < connector_names.size(); ++i)
        {
            const auto & name = connector_names[i];
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON storage import connector {}/{}: '{}'",
                    i + 1,
                    connector_names.size(),
                    name);
            }

            try
            {
                if(!co_await ensureConnectorImported(evm, registry, name, storage_path, context))
                {
                    success = false;
                }
            }
            catch(const std::exception & e)
            {
                spdlog::error("Unhandled exception while importing connector '{}': {}", name, e.what());
                success = false;
            }
            catch(...)
            {
                spdlog::error("Unhandled unknown exception while importing connector '{}'", name);
                success = false;
            }
        }

        if(!co_await flushPendingTransformations(registry, context, true))
        {
            success = false;
        }
        if(!co_await flushPendingConditions(registry, context, true))
        {
            success = false;
        }
        if(!co_await flushPendingConnectors(registry, context, true))
        {
            success = false;
        }

        spdlog::info("JSON storage import finished with status={}", success ? "success" : "failure");
        co_return success;
    }

    asio::awaitable<bool> ensureTransformationImported(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        JsonImportContext & context)
    {
        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure transformation '{}': begin", name);
        }

        if(context.imported_transformations.contains(name))
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure transformation '{}': already imported in current session", name);
            }
            co_return true;
        }

        if(context.importing_transformations.contains(name))
        {
            spdlog::error("Transformation import cycle detected for '{}'", name);
            co_return false;
        }

        const bool exists_in_db = co_await registry.hasTransformation(name);
        if(exists_in_db)
        {
            context.imported_transformations.insert(name);
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure transformation '{}': found in DB, skipping JSON deploy", name);
            }
            co_return true;
        }

        const auto json_it = context.transformations.find(name);
        if(json_it == context.transformations.end())
        {
            spdlog::error("Transformation '{}' not found in DB or JSON storage", name);
            co_return false;
        }

        context.importing_transformations.insert(name);

        const auto deploy_result = co_await deployTransformation(
            evm,
            registry,
            json_it->second,
            storage_path,
            false,
            false);

        context.importing_transformations.erase(name);

        if(!deploy_result)
        {
            spdlog::error(
                "Failed to import transformation '{}' from JSON into DB: {}",
                name,
                static_cast<int>(deploy_result.error().kind));
            co_return false;
        }

        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure transformation '{}': deployed at {}", name, evmc::hex(deploy_result.value()));
        }

        context.pending_transformations.emplace_back(deploy_result.value(), json_it->second);
        if(!co_await flushPendingTransformations(registry, context, false))
        {
            co_return false;
        }

        context.imported_transformations.insert(name);
        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure transformation '{}': complete", name);
        }
        co_return true;
    }

    asio::awaitable<bool> ensureConditionImported(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        JsonImportContext & context)
    {
        if(name.empty())
        {
            co_return true;
        }

        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure condition '{}': begin", name);
        }

        if(context.imported_conditions.contains(name))
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure condition '{}': already imported in current session", name);
            }
            co_return true;
        }

        if(context.importing_conditions.contains(name))
        {
            spdlog::error("Condition import cycle detected for '{}'", name);
            co_return false;
        }

        const bool exists_in_db = co_await registry.hasCondition(name);
        if(exists_in_db)
        {
            context.imported_conditions.insert(name);
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure condition '{}': found in DB, skipping JSON deploy", name);
            }
            co_return true;
        }

        const auto json_it = context.conditions.find(name);
        if(json_it == context.conditions.end())
        {
            spdlog::error("Condition '{}' not found in DB or JSON storage", name);
            co_return false;
        }

        context.importing_conditions.insert(name);

        const auto deploy_result = co_await deployCondition(
            evm,
            registry,
            json_it->second,
            storage_path,
            false,
            false);

        context.importing_conditions.erase(name);

        if(!deploy_result)
        {
            spdlog::error(
                "Failed to import condition '{}' from JSON into DB: {}",
                name,
                static_cast<int>(deploy_result.error().kind));
            co_return false;
        }

        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure condition '{}': deployed at {}", name, evmc::hex(deploy_result.value()));
        }

        context.pending_conditions.emplace_back(deploy_result.value(), json_it->second);
        if(!co_await flushPendingConditions(registry, context, false))
        {
            co_return false;
        }

        context.imported_conditions.insert(name);
        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure condition '{}': complete", name);
        }
        co_return true;
    }

    asio::awaitable<bool> ensureConnectorImported(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        JsonImportContext & context)
    {
        StackPushGuard stack_guard(context.connector_import_stack, name);
        const std::size_t depth = context.connector_import_stack.size();

        if(depth > MAX_CONNECTOR_IMPORT_DEPTH)
        {
            spdlog::error(
                "Connector import recursion depth overflow (depth={}, max={}): {}",
                depth,
                MAX_CONNECTOR_IMPORT_DEPTH,
                formatDependencyStack(context.connector_import_stack));
            co_return false;
        }

        if(context.trace_enabled)
        {
            spdlog::info(
                "JSON import ensure connector '{}': begin (depth={}, path={})",
                name,
                depth,
                formatDependencyStack(context.connector_import_stack));
        }

        if(context.imported_connectors.contains(name))
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure connector '{}': already imported in current session", name);
            }
            co_return true;
        }

        if(context.importing_connectors.contains(name))
        {
            spdlog::error(
                "Connector import cycle detected for '{}': {}",
                name,
                formatDependencyStack(context.connector_import_stack));
            co_return false;
        }

        const bool exists_in_db = co_await registry.hasConnector(name);
        if(exists_in_db)
        {
            context.imported_connectors.insert(name);
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure connector '{}': found in DB, skipping JSON deploy", name);
            }
            co_return true;
        }

        const auto json_it = context.connectors.find(name);
        if(json_it == context.connectors.end())
        {
            spdlog::error("Connector '{}' not found in DB or JSON storage", name);
            co_return false;
        }

        context.importing_connectors.insert(name);
        const ConnectorRecord & connector_record = json_it->second;
        const Connector & connector = connector_record.connector();

        bool ok = true;

        for(const auto & dimension : connector.dimensions())
        {
            for(const auto & transformation : dimension.transformations())
            {
                const std::string & transformation_name = transformation.name();
                if(transformation_name.empty())
                {
                    continue;
                }

                if(context.trace_enabled)
                {
                    spdlog::info(
                        "JSON import connector '{}' requires transformation '{}'",
                        name,
                        transformation_name);
                }

                if(!co_await ensureTransformationImported(
                    evm,
                    registry,
                    transformation_name,
                    storage_path,
                    context))
                {
                    ok = false;
                    break;
                }

                if(!co_await ensureTransformationDeployed(
                    evm,
                    registry,
                    transformation_name,
                    storage_path))
                {
                    ok = false;
                    break;
                }
            }

            if(!ok)
            {
                break;
            }

            if(!dimension.composite().empty())
            {
                if(context.trace_enabled)
                {
                    spdlog::info(
                        "JSON import connector '{}' requires composite connector '{}'",
                        name,
                        dimension.composite());
                }

                if(!co_await ensureConnectorImported(
                    evm,
                    registry,
                    dimension.composite(),
                    storage_path,
                    context))
                {
                    ok = false;
                    break;
                }

                if(!co_await ensureConnectorDeployed(
                    evm,
                    registry,
                    dimension.composite(),
                    storage_path))
                {
                    ok = false;
                    break;
                }
            }

            for(const auto & [_, binding_target] : dimension.bindings())
            {
                if(binding_target.empty())
                {
                    continue;
                }

                if(context.trace_enabled)
                {
                    spdlog::info(
                        "JSON import connector '{}' requires binding target connector '{}'",
                        name,
                        binding_target);
                }

                if(!co_await ensureConnectorImported(
                    evm,
                    registry,
                    binding_target,
                    storage_path,
                    context))
                {
                    ok = false;
                    break;
                }

                if(!co_await ensureConnectorDeployed(
                    evm,
                    registry,
                    binding_target,
                    storage_path))
                {
                    ok = false;
                    break;
                }
            }

            if(!ok)
            {
                break;
            }
        }

        if(ok && !connector.condition_name().empty())
        {
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON import connector '{}' requires condition '{}'",
                    name,
                    connector.condition_name());
            }

            if(!co_await ensureConditionImported(
                evm,
                registry,
                connector.condition_name(),
                storage_path,
                context))
            {
                ok = false;
            }
            else if(!co_await ensureConditionDeployed(
                evm,
                registry,
                connector.condition_name(),
                storage_path))
            {
                ok = false;
            }
        }

        if(ok)
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import connector '{}': deploying from JSON", name);
            }
            const auto deploy_result = co_await deployConnector(
                evm,
                registry,
                connector_record,
                storage_path,
                false,
                false);
            if(!deploy_result)
            {
                spdlog::error(
                    "Failed to import connector '{}' from JSON into DB: {}",
                    name,
                    static_cast<int>(deploy_result.error().kind));
                ok = false;
            }
            else
            {
                if(context.trace_enabled)
                {
                    spdlog::info("JSON import connector '{}': deployed at {}", name, evmc::hex(deploy_result.value()));
                }
                context.pending_connectors.emplace_back(deploy_result.value(), connector_record);
                if(!co_await flushPendingConnectors(registry, context, false))
                {
                    ok = false;
                }
            }
        }

        context.importing_connectors.erase(name);

        if(!ok)
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure connector '{}': failed", name);
            }
            co_return false;
        }

        context.imported_connectors.insert(name);
        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure connector '{}': complete", name);
        }
        co_return true;
    }

    asio::awaitable<bool> ensureConnectorDeployedImpl(
        evm::EVM & evm,
        storage::Registry & registry,
        const std::string & name,
        const std::filesystem::path & storage_path,
        ConnectorEnsureContext & context)
    {
        StackPushGuard stack_guard(context.connector_deploy_stack, name);
        const std::size_t depth = context.connector_deploy_stack.size();

        if(depth > MAX_CONNECTOR_IMPORT_DEPTH)
        {
            spdlog::error(
                "Connector deploy recursion depth overflow (depth={}, max={}): {}",
                depth,
                MAX_CONNECTOR_IMPORT_DEPTH,
                formatDependencyStack(context.connector_deploy_stack));
            co_return false;
        }

        if(context.trace_enabled)
        {
            spdlog::info(
                "JSON import ensure deployed connector '{}': begin (depth={}, path={})",
                name,
                depth,
                formatDependencyStack(context.connector_deploy_stack));
        }

        if(name.empty())
        {
            spdlog::error("Cannot deploy connector with empty name");
            co_return false;
        }

        if(context.done.contains(name))
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure deployed connector '{}': already deployed in current walk", name);
            }
            co_return true;
        }

        if(context.visiting.contains(name))
        {
            spdlog::error(
                "Connector deployment cycle detected for '{}': {}",
                name,
                formatDependencyStack(context.connector_deploy_stack));
            co_return false;
        }

        const auto contains_res = co_await containsRegistryEntry(evm, "containsConnector(string)", name);
        if(!contains_res.has_value())
        {
            co_return false;
        }
        if(*contains_res)
        {
            context.done.insert(name);
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure deployed connector '{}': already present on-chain", name);
            }
            co_return true;
        }

        const auto record_handle_opt = co_await registry.getConnectorRecordHandle(name);
        if(!record_handle_opt.has_value() || !(*record_handle_opt))
        {
            spdlog::error("Connector '{}' is missing in registry DB", name);
            co_return false;
        }

        context.visiting.insert(name);

        const Connector & connector = (*record_handle_opt)->connector();
        bool ok = true;

        for(const auto & dimension : connector.dimensions())
        {
            for(const auto & transformation : dimension.transformations())
            {
                const auto & transformation_name = transformation.name();
                if(transformation_name.empty())
                {
                    continue;
                }

                if(context.trace_enabled)
                {
                    spdlog::info(
                        "JSON import deploy connector '{}' requires deployed transformation '{}'",
                        name,
                        transformation_name);
                }

                if(!co_await ensureTransformationDeployed(
                    evm,
                    registry,
                    transformation_name,
                    storage_path))
                {
                    ok = false;
                    break;
                }
            }

            if(!ok)
            {
                break;
            }

            if(!dimension.composite().empty())
            {
                if(context.trace_enabled)
                {
                    spdlog::info(
                        "JSON import deploy connector '{}' requires deployed composite '{}'",
                        name,
                        dimension.composite());
                }

                if(!co_await ensureConnectorDeployedImpl(
                    evm,
                    registry,
                    dimension.composite(),
                    storage_path,
                    context))
                {
                    ok = false;
                    break;
                }
            }

            for(const auto & [_, binding_target] : dimension.bindings())
            {
                if(binding_target.empty())
                {
                    continue;
                }

                if(context.trace_enabled)
                {
                    spdlog::info(
                        "JSON import deploy connector '{}' requires deployed binding target '{}'",
                        name,
                        binding_target);
                }

                if(!co_await ensureConnectorDeployedImpl(
                    evm,
                    registry,
                    binding_target,
                    storage_path,
                    context))
                {
                    ok = false;
                    break;
                }
            }

            if(!ok)
            {
                break;
            }
        }

        if(ok && !connector.condition_name().empty())
        {
            if(context.trace_enabled)
            {
                spdlog::info(
                    "JSON import deploy connector '{}' requires deployed condition '{}'",
                    name,
                    connector.condition_name());
            }

            if(!co_await ensureConditionDeployed(
                evm,
                registry,
                connector.condition_name(),
                storage_path))
            {
                ok = false;
            }
        }

        if(ok)
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import deploy connector '{}': deploying from DB record", name);
            }
            const auto deploy_result = co_await deployConnectorWithContext(
                evm,
                registry,
                *(*record_handle_opt),
                storage_path,
                false,
                false,
                context);
            if(!deploy_result &&
                deploy_result.error().kind != pt::PTDeployError::Kind::CONNECTOR_ALREADY_REGISTERED)
            {
                spdlog::error(
                    "Failed to deploy connector '{}' from DB for runtime use: {}",
                    name,
                    static_cast<int>(deploy_result.error().kind));
                ok = false;
            }
            else if(context.trace_enabled)
            {
                spdlog::info("JSON import deploy connector '{}': deployed at {}", name, evmc::hex(deploy_result.value()));
            }
        }

        context.visiting.erase(name);
        if(!ok)
        {
            if(context.trace_enabled)
            {
                spdlog::info("JSON import ensure deployed connector '{}': failed", name);
            }
            co_return false;
        }

        context.done.insert(name);
        if(context.trace_enabled)
        {
            spdlog::info("JSON import ensure deployed connector '{}': complete", name);
        }
        co_return true;
    }

}
