#include "loader.hpp"

#include <array>
#include <type_traits>

namespace dcn::loader
{
    namespace
    {
        // Bump when PT Solidity changes affect generated bytecode semantics to invalidate cached artifacts.
        constexpr const char* PT_BUILD_VERSION = "constructors-v2-slot-propagation";

        const std::array<std::string, 3> PT_STORAGE_ENTITY_DIRS{
            "connectors",
            "transformations",
            "conditions"
        };
    }

    template<class T>
    static absl::flat_hash_map<std::string, T> _loadJSONRecords(std::filesystem::path dir)
    {
        absl::flat_hash_map<std::string, T> loaded_data;
        parse::Result<T> loaded_result;
        
        bool success = true;

        try {
            for (const auto& entry : std::filesystem::directory_iterator(dir)) 
            {
                if (!entry.is_regular_file() || entry.path().extension() != ".json") continue;
                
                spdlog::debug(std::format("Found JSON file: {}", entry.path().string()));

                std::ifstream file(entry.path());

                if (!file.is_open()) {
                    spdlog::error(std::format("Failed to open file: {}", entry.path().string()));
                    continue;
                }

                std::string json((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
                file.close();

                loaded_result = parse::parseFromJson<T>(json, parse::use_protobuf);
                if(!loaded_result)
                {
                    spdlog::error(std::format("Failed to parse JSON: {}", json));
                    continue;
                }

                loaded_data.try_emplace(entry.path().stem().string(), std::move(*loaded_result));
            }
        } 
        catch (const std::filesystem::filesystem_error& e) 
        {
            spdlog::error(std::format("Filesystem error: {}", e.what()));
            success = false;
        } 
        catch (const std::exception& e) 
        {
            spdlog::error(std::format("Exception: {}", e.what()));
            success = false;
        }

        if(!success)
        {
            return {};
        }

        return loaded_data;
    }

    static void _removeFileNoThrow(const std::filesystem::path & file_path)
    {
        std::error_code ec;
        std::filesystem::remove(file_path, ec);
        if(ec)
        {
            spdlog::debug("Failed to remove '{}': {}", file_path.string(), ec.message());
        }
    }

    static void _loadCleanup(const std::filesystem::path & out_dir, const std::string & name)
    {
        // remove binary file
        _removeFileNoThrow(out_dir / (name + ".bin"));
        _removeFileNoThrow(out_dir / (name + ".abi"));
    }

    bool ensurePTBuildVersion(const std::filesystem::path & storage_path)
    {
        const std::filesystem::path marker_path = storage_path / "pt_solidity_build_version";

        std::string current_version;
        if(std::filesystem::exists(marker_path))
        {
            std::ifstream marker_in(marker_path);
            if(marker_in.is_open())
            {
                std::getline(marker_in, current_version);
            }
        }

        if(current_version == PT_BUILD_VERSION)
        {
            spdlog::debug("PT Solidity build cache version is up-to-date: {}", PT_BUILD_VERSION);
            return true;
        }

        spdlog::info(
            "PT Solidity build cache version changed from '{}' to '{}'. Cleaning stale build artifacts.",
            current_version.empty() ? "<none>" : current_version,
            PT_BUILD_VERSION
        );

        try
        {
            for(const std::string & entity_dir : PT_STORAGE_ENTITY_DIRS)
            {
                const std::filesystem::path build_dir = storage_path / entity_dir / "build";
                std::size_t removed_count = 0;

                if(std::filesystem::exists(build_dir))
                {
                    for(const auto & entry : std::filesystem::directory_iterator(build_dir))
                    {
                        if(!entry.is_regular_file())
                        {
                            continue;
                        }

                        const std::filesystem::path file_path = entry.path();
                        const std::string ext = file_path.extension().string();
                        if(ext == ".bin" || ext == ".abi")
                        {
                            std::filesystem::remove(file_path);
                            ++removed_count;
                        }
                    }
                }

                spdlog::info("PT build cleanup '{}': removed {} cached artifacts", entity_dir, removed_count);
            }
        }
        catch(const std::filesystem::filesystem_error & e)
        {
            spdlog::error("Failed to cleanup PT build artifacts: {}", e.what());
            return false;
        }

        std::ofstream marker_out(marker_path, std::ios::out | std::ios::trunc);
        if(!marker_out.is_open())
        {
            spdlog::error("Failed to write PT build version marker '{}'", marker_path.string());
            return false;
        }

        marker_out << PT_BUILD_VERSION;
        marker_out.close();

        spdlog::info("PT Solidity build cache marker updated: {}", PT_BUILD_VERSION);
        return true;
    }

    template<class RecordType>
    static asio::awaitable<bool> _saveJsonRecord(const std::string & name, RecordType record, const std::filesystem::path out_dir)
    {
        if(std::filesystem::exists(out_dir) == false)
        {
            spdlog::error("Directory {} does not exists", out_dir.string());
            co_return false;
        }

        const auto parsing_result = parse::parseToJson(record, parse::use_protobuf);
        if(!parsing_result)
        {
            spdlog::error("Failed to parse record `{}`", name);
            co_return false;
        }

        std::ofstream output_file(out_dir / (name + ".json"), std::ios::out | std::ios::trunc);

        output_file << *parsing_result;
        output_file.close();

        co_return true;
    }

    // template<class RecordType, class CodeGeneratorFunc>
    // static asio::awaitable<bool> _compileRecord(const std::string & name, RecordType record, 
    //     CodeGeneratorFunc && constructSolidityCode,
    //     const std::filesystem::path bin_dir)
    // {
    //     // if binary file does not exist
    //     if(std::filesystem::exists(bin_dir / (name + ".bin")) == false)
    //     {
    //         // there is a need for compile code
    //         const std::filesystem::path code_path = bin_dir / (name + ".sol");

    //         // create code file
    //         std::ofstream out_file(code_path); 
    //         if(!out_file.is_open())
    //         {
    //             spdlog::error("Failed to create file");
    //             co_return std::unexpected(evm::DeployError{});
    //         }

    //         out_file << constructSolidityCode(record.connector());
    //         out_file.close();

    //         // compile code
    //         if(!co_await evm.compile(code_path, bin_dir, file::getPTPath()/ "contracts"))
    //         {
    //             spdlog::error("Failed to compile code");
    //             // remove code file
    //             std::filesystem::remove(code_path);
    //             co_return std::unexpected(evm::DeployError{evm::DeployError::Kind::COMPILATION_ERROR});
    //         }

    //         // remove code file
    //         std::filesystem::remove(code_path);
    //     }
    // }



    template<class T, class InternalGetter, class SolidityCodeCtor>
    static asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> _deployObjectLocally(evm::EVM & evm, 
        registry::Registry & registry, T object, InternalGetter getter,
        const std::filesystem::path out_dir, SolidityCodeCtor solidity_code_ctor, pt::PTDeployError::Kind expected_conflict_error
    )
    {
        using Internal_t = std::invoke_result_t<InternalGetter, T>;
        const Internal_t & internal = std::invoke(getter, object);

        if(internal.name().empty())
        {
            spdlog::error("Object name is empty");
            co_return std::unexpected(pt::PTDeployError{
                .kind = pt::PTDeployError::Kind::INVALID_INPUT});
        }

        const std::string name = internal.name();

        const auto address_result = evmc::from_hex<chain::Address>(object.owner());
        if(!address_result)
        {
            spdlog::error("Failed to parse address");
            co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
        }
        const auto & address = *address_result;

        const std::filesystem::path bin_dir = out_dir / "build";

        if(std::filesystem::exists(bin_dir) == false)
        {
            spdlog::error("Directory {} does not exists", bin_dir.string());
            co_return std::unexpected(pt::PTDeployError{});
        }

        // if binary file does not exist
        const bool binary_already_exists = std::filesystem::exists(bin_dir / (name + ".bin"));
        const auto cleanup_new_build_artifacts = [&]()
        {
            if(!binary_already_exists)
            {
                _loadCleanup(bin_dir, name);
            }
        };

        if(binary_already_exists == false)
        {
            // there is a need for compile code
            const std::filesystem::path code_path = bin_dir / (name + ".sol");

            // create code file
            std::ofstream out_file(code_path); 
            if(!out_file.is_open())
            {
                spdlog::error("Failed to create file");
                co_return std::unexpected(pt::PTDeployError{});
            }

            using SolidityCodeResult_t = std::decay_t<std::invoke_result_t<SolidityCodeCtor, Internal_t>>;
            const auto solidity_code_result = std::invoke(std::forward<SolidityCodeCtor>(solidity_code_ctor), internal);

            std::string solidity_code;
            if constexpr(std::is_same_v<SolidityCodeResult_t, parse::Result<std::string>>)
            {
                if(!solidity_code_result)
                {
                    spdlog::error(
                        "Failed to construct Solidity code for `{}`: parse error kind={} ({})",
                        name,
                        static_cast<int>(solidity_code_result.error().kind),
                        solidity_code_result.error().message);
                    out_file.close();
                    _removeFileNoThrow(code_path);
                    co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
                }

                solidity_code = *solidity_code_result;
            }
            else if constexpr(std::is_same_v<SolidityCodeResult_t, std::string>)
            {
                solidity_code = solidity_code_result;
                if(solidity_code.empty())
                {
                    spdlog::error("Failed to construct Solidity code for `{}`: empty source", name);
                    out_file.close();
                    _removeFileNoThrow(code_path);
                    co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
                }
            }
            else
            {
                static_assert(utils::always_false<SolidityCodeResult_t>, "Unsupported Solidity code constructor return type");
            }

            out_file << solidity_code;
            if(!out_file.good())
            {
                spdlog::error("Failed to write Solidity source file '{}'", code_path.string());
                out_file.close();
                _removeFileNoThrow(code_path);
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
            }
            out_file.close();
            if(out_file.fail())
            {
                spdlog::error("Failed to flush Solidity source file '{}'", code_path.string());
                _removeFileNoThrow(code_path);
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
            }

            // compile code
            if(!co_await evm.compile(code_path, bin_dir, evm.getPTPath() / "contracts", evm.getPTPath() / "node_modules"))
            {
                spdlog::error("Failed to compile code");
                // remove code file
                _removeFileNoThrow(code_path);
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{ pt::PTDeployError::Kind::INVALID_INPUT});
            }

            // remove code file
            _removeFileNoThrow(code_path);
        }

        co_await evm.addAccount(address, evm::DEFAULT_GAS_LIMIT);
        co_await evm.setGas(address, evm::DEFAULT_GAS_LIMIT);
        
        std::vector<std::uint8_t> ctor_args = evm::encodeAsArg(evm.getRegistryAddress());
        auto deploy_res = co_await evm.deploy(
            bin_dir / (name + ".bin"),
            address, 
            std::move(ctor_args),
            evm::DEFAULT_GAS_LIMIT, 
            0);

        if(!deploy_res)
        {
            spdlog::error(std::format("Failed to deploy object: {}", deploy_res.error().kind));
            const auto & error = deploy_res.error();
            const auto pt_error = parse::decodeBytes<pt::PTDeployError>(error.result_bytes);

            if(!pt_error)
            {
                std::string output_hex = "<empty>";
                if(!error.result_bytes.empty())
                {
                    output_hex = evmc::hex(evmc::bytes_view{error.result_bytes.data(), error.result_bytes.size()});
                }

                spdlog::error(std::format(
                    "Failed to parse PTDeployError: {} ({}) output={}",
                    pt_error.error().kind,
                    pt_error.error().message,
                    output_hex));
                cleanup_new_build_artifacts();
                co_return std::unexpected(pt::PTDeployError{});
            }

            if(pt_error->kind != expected_conflict_error)
            {
                cleanup_new_build_artifacts();
            }

            co_return std::unexpected(pt_error.value());
        }

        const auto object_address = deploy_res.value();
        spdlog::info("Object address '{}': {}", name, evmc::hex(object_address));

        const auto owner_result = co_await fetchOwner(evm, object_address);

        // check execution status
        if(!owner_result)
        {
            spdlog::error(std::format("Failed to fetch owner {}", owner_result.error().kind));

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{});
        }

        const auto owner_address_res = chain::readAddressWord(owner_result.value());

        if(!owner_address_res)
        {
            spdlog::error("Failed to parse owner address");

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
        }

        const auto & owner_address = owner_address_res.value();

        if(owner_address != address)
        {
            spdlog::error("Owner address mismatch");

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{pt::PTDeployError::Kind::INVALID_INPUT});
        }

        if(!co_await registry.add(object_address, object))
        {
            spdlog::error("Failed to add object '{}'", name);

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{});
        }
        
        if(!co_await _saveJsonRecord(name, std::move(object), out_dir))
        {
            spdlog::error("Failed to save object json '{}'", name);

            // remove binary file
            cleanup_new_build_artifacts();

            co_return std::unexpected(pt::PTDeployError{});
        }

        spdlog::debug("Object '{}' added", name);
        co_return object_address;
    }


    asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployConnector(evm::EVM & evm, registry::Registry & registry, ConnectorRecord connector_record, const std::filesystem::path & storage_path)
    {
        return _deployObjectLocally(evm,
            registry, 
            std::move(connector_record), 
            &ConnectorRecord::connector, 
            storage_path / "connectors",
            &constructConnectorSolidityCode,
            pt::PTDeployError::Kind::CONNECTOR_ALREADY_REGISTERED);
    }

    asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployTransformation(evm::EVM & evm, registry::Registry & registry, TransformationRecord transformation_record, const std::filesystem::path & storage_path)
    {
        return _deployObjectLocally(evm,
            registry, 
            std::move(transformation_record), 
            &TransformationRecord::transformation, 
            storage_path / "transformations",
            &constructTransformationSolidityCode,
            pt::PTDeployError::Kind::TRANSFORMATION_ALREADY_REGISTERED);
    }


    asio::awaitable<std::expected<chain::Address, pt::PTDeployError>> deployCondition(evm::EVM & evm, registry::Registry & registry, ConditionRecord condition_record, const std::filesystem::path & storage_path)
    {
        return _deployObjectLocally(evm,
            registry, 
            std::move(condition_record), 
            &ConditionRecord::condition, 
            storage_path / "conditions",
            &constructConditionSolidityCode,
            pt::PTDeployError::Kind::CONDITION_ALREADY_REGISTERED);
    }


    asio::awaitable<bool> loadStoredConnectors(evm::EVM & evm, registry::Registry & registry, const std::filesystem::path & storage_path)
    {
        spdlog::info("Loading stored connectors...");

        auto loaded_connectors = _loadJSONRecords<ConnectorRecord>(storage_path / "connectors");
        if(loaded_connectors.empty())
        {
            co_return false;
        }

        const auto sorted_connectors = utils::topologicalSort<ConnectorRecord, std::string, std::vector>(
                loaded_connectors,
                [](const ConnectorRecord & record)
                {
                    std::vector<std::string> dependencies;
                    dependencies.reserve(static_cast<std::size_t>(record.connector().dimensions_size()));
                    for(const auto & dimension : record.connector().dimensions())
                    {
                        if(dimension.composite().empty())
                        {
                            if(dimension.bindings_size() != 0)
                            {
                                for(const auto & [_, binding_target] : dimension.bindings())
                                {
                                    if(!binding_target.empty())
                                    {
                                        dependencies.push_back(binding_target);
                                    }
                                }
                            }
                            continue;
                        }

                        dependencies.push_back(dimension.composite());

                        for(const auto & [_, binding_target] : dimension.bindings())
                        {
                            if(binding_target.empty())
                            {
                                continue;
                            }
                            dependencies.push_back(binding_target);
                        }
                    }
                    return dependencies;
                },
                [](const std::string & composite) {return composite;}
            );

        bool success = true;
        std::size_t i = 0;
        const std::size_t batch_size = (sorted_connectors.size() / 100) + 1;
        assert(batch_size > 0);
        
        for(const auto & name : sorted_connectors)
        {
            if(!co_await deployConnector(evm, registry, std::move(loaded_connectors.at(name)), storage_path))
            {
                spdlog::error("Failed to deploy connector `{}`", name);
                success = false;
            }

            if(++i % batch_size == 0) {spdlog::debug("{}/{} connectors loaded", i, loaded_connectors.size());}
        }

        co_return success;
    }


    asio::awaitable<bool> loadStoredTransformations(evm::EVM & evm, registry::Registry & registry, const std::filesystem::path & storage_path)
    {
        spdlog::info("Loading stored transformations...");

        auto loaded_transformations = _loadJSONRecords<TransformationRecord>(storage_path / "transformations");
        if(loaded_transformations.empty())
        {
            co_return false;
        }

        bool success = true;
        std::size_t i = 0;
        const std::size_t batch_size = (loaded_transformations.size() / 100) + 1;
        assert(batch_size > 0);

        for(auto & [name, transformation] : loaded_transformations)
        {
            if(!co_await deployTransformation(evm, registry, std::move(transformation), storage_path))
            {
                spdlog::error("Failed to deploy transformation `{}`", name);
                success = false;
            }

            if(++i % batch_size == 0) {spdlog::debug("{}/{} transformations loaded", i, loaded_transformations.size());}
        }

        co_return success;
    }

    asio::awaitable<bool> loadStoredConditions(evm::EVM & evm, registry::Registry & registry, const std::filesystem::path & storage_path)
    {
        spdlog::info("Loading stored conditions...");

        auto loaded_conditions = _loadJSONRecords<ConditionRecord>(storage_path / "conditions");
        if(loaded_conditions.empty())
        {
            co_return false;
        }

        bool success = true;
        std::size_t i = 0;
        const std::size_t batch_size = (loaded_conditions.size() / 100) + 1;
        assert(batch_size > 0);

        for(auto & [name, condition] : loaded_conditions)
        {
            if(!co_await deployCondition(evm, registry, std::move(condition), storage_path))
            {
                spdlog::error("Failed to deploy condition `{}`", name);
                success = false;
            }

            if(++i % batch_size == 0) {spdlog::debug("{}/{} conditions loaded", i, loaded_conditions.size());}
        }

        co_return success;
    }

}
