name: Build (linux-x64 Release)

on:
  workflow_run:
    workflows: ["Test (linux Debug)"]
    types: [completed]
    branches: [ main ]

jobs:
  build-linux-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake build-essential libssl-dev npm

    - name: Configure and build (Release)
      run: |
        cmake -S . -B build-linux-release -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        cmake --build build-linux-release --config RelWithDebInfo --target install -j 4

    - name: Pack install directory into tarball
      run: |
        tar -czf dcn-server-linux-x64.tar.gz -C install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dcn-server-linux-x64
        path: dcn-server-linux-x64.tar.gz 
