name: Build (windows-x64 Release)

on:
  workflow_run:
    workflows: ["Test (windows Debug)"]
    types: [completed]
    branches: [ main ]

jobs:
  build-windows-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure and build (RelWithDebInfo)
      run: |
        cmake -S . -B build-windows-release -A x64 -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build build-windows-release --config RelWithDebInfo --target install -j 4

    - name: Pack install directory into tarball
      run: |
        tar -czf dcn-server-windows-x64.tar.gz -C install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dcn-server-windows-x64
        path: dcn-server-windows-x64.tar.gz 
